export const GET_TRIP = 'GET_TRIP'
export const GET_TRIPS_SUCCESS = 'GET_TRIPS_SUCCESS'
export const CREATE_TRIP = 'CREATE_TRIP'
export const UPDATE_TRIP = 'UPDATE_TRIP'
export const ADD_MEDIA = 'ADD_MEDIA'
